"""Google sign-in link + the profile fields that were missing.

Revision ID: 2c2168e1d70e
Revises: 0001_baseline
Create Date: 2026-08-05 12:59:24.928968+00:00

Adds, on `users`:
  * `supabase_user_id` — Supabase `auth.users.id` for accounts created or linked
    through Google. UNIQUE, so one Google identity cannot be attached to two
    application accounts.
  * `avatar_url`, `updated_at` — the two profile fields the table did not have.
  * `password_hash` becomes NULLABLE, because an account created through Google has
    no password. NULL states that plainly; a placeholder hash would be
    indistinguishable from a real one.

Two corrections were made to the autogenerated version, both of which would have
produced a downgrade that fails when run:

  1. The constraint was created and dropped with `None` as its name. Creating works
     (Alembic invents a name) but `drop_constraint(None, ...)` cannot resolve one, so
     the downgrade would error. It is named explicitly here.
  2. The downgrade restored `password_hash NOT NULL` unconditionally. Any account
     created through Google has NULL there — exactly what this migration enables — so
     the downgrade would abort on a constraint violation partway through. It now
     checks first and stops with an explanation instead of failing obscurely, because
     the alternative is silently deleting real customer accounts.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "2c2168e1d70e"
down_revision: Union[str, None] = "0001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Named so the downgrade can drop it. See note 1 above.
_SUPABASE_UID_UNIQUE = "uq_users_supabase_user_id"


def upgrade() -> None:
    op.add_column("users", sa.Column("supabase_user_id", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("avatar_url", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_unique_constraint(_SUPABASE_UID_UNIQUE, "users", ["supabase_user_id"])


def downgrade() -> None:
    connection = op.get_bind()

    # Restoring NOT NULL is impossible while password-less (Google) accounts exist,
    # and forcing it would mean destroying them. Stop with something an operator can
    # act on.
    passwordless = connection.execute(
        sa.text("SELECT count(*) FROM users WHERE password_hash IS NULL")
    ).scalar()
    if passwordless:
        raise RuntimeError(
            f"Cannot downgrade: {passwordless} account(s) were created through Google "
            "sign-in and have no password, so `users.password_hash` cannot be made "
            "NOT NULL again. Decide deliberately first — either set a password for "
            "those accounts (they can use 'forgot password' to choose one) or remove "
            "them — then re-run this downgrade."
        )

    op.drop_constraint(_SUPABASE_UID_UNIQUE, "users", type_="unique")
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "updated_at")
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "supabase_user_id")
