"""Patient provenance: who created each contact, the agent or a person.

Revision ID: e490979d4cb1
Revises: 3a7f91c4e2b8

Brings the database in line with the Staff Panel work merged from product1/main,
which added these two columns to `backend/db/schema.sql` and to the model but had no
migration — that file is not executed by the application, and `create_all` does not
ALTER an existing table. So the columns were missing from the live database while the
code already wrote to them: `repository.py` sets `source="agent"` on every contact the
voice agent creates, which would have failed with
`column "source" of relation "patients" does not exist`.

  * `patients.source`     — 'agent' (created during a call) | 'manual' (created by a
                            person in the dashboard). NOT NULL, so it carries a
                            server_default for the rows that already exist.
  * `patients.created_by` — the user who added it by hand; NULL for agent-created
                            rows and for anything predating this column. ON DELETE
                            SET NULL so removing a staff member does not delete
                            patient records.

Corrected from the autogenerated version: the foreign key was created and dropped
with `None` as its name. Creating works (Alembic invents one) but
`drop_constraint(None, ...)` cannot resolve a name, so the downgrade would fail. It is
named explicitly here — the same defect appeared in the previous migration, so it is
worth watching for whenever autogenerate produces a constraint.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "e490979d4cb1"
down_revision: Union[str, None] = "3a7f91c4e2b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_CREATED_BY_FK = "fk_patients_created_by_users"
_CREATED_BY_IX = "ix_patients_created_by"


def upgrade() -> None:
    op.add_column(
        "patients",
        sa.Column(
            "source",
            sa.String(length=20),
            # Required: the column is NOT NULL and the table already holds rows.
            server_default=sa.text("'agent'"),
            nullable=False,
        ),
    )
    op.add_column("patients", sa.Column("created_by", sa.UUID(), nullable=True))
    op.create_index(_CREATED_BY_IX, "patients", ["created_by"], unique=False)
    op.create_foreign_key(
        _CREATED_BY_FK, "patients", "users", ["created_by"], ["id"], ondelete="SET NULL"
    )


def downgrade() -> None:
    # Drops provenance information only; no patient record is removed.
    op.drop_constraint(_CREATED_BY_FK, "patients", type_="foreignkey")
    op.drop_index(_CREATED_BY_IX, table_name="patients")
    op.drop_column("patients", "created_by")
    op.drop_column("patients", "source")
